const movies = [
  {
    id: 0,
    title: "The power of dog",
    summary: `Charismatic rancher Phil Burbank inspires fear and awe in those around him. When his brother brings home a new wife and her son, Phil torments them until he finds himself exposed to the possibility of love.`,
    genre: "Western",
    rate: 8.4,
    price: 9.16,
    src: require("../assets/images/ThePowerOfDog.jpg"),
  },
  {
    id: 1,
    title: "Coda",
    summary: `As a CODA (Child of Deaf Adults) Ruby is the only hearing person in her deaf family. When the family's fishing business is threatened, Ruby finds herself torn between pursuing her passion at Berklee College of Music and her fear of abandoning her parents.`,
    genre: "Comedy",
    rate: 8.1,
    price: 9.99,
    src: require("../assets/images/Coda.jpg"),
  },
  {
    id: 2,
    title: "Dune",
    summary: `A noble family becomes embroiled in a war for control over the galaxy's most valuable asset while its heir becomes troubled by visions of a dark future.`,
    genre: "Action",
    rate: 8.4,
    price: 12.25,
    src: require("../assets/images/Dune.jpg"),
  },
  {
    id: 3,
    title: "Spidrer Man: No Way Home ",
    summary: `With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.`,
    genre: "Action",
    rate: 7.8,
    price: 17.99,
    src: require("../assets/images/Spider.man.no.way.home.jpg"),
  },
  {
    id: 4,
    title: "Turning Red",
    summary: `A 13-year-old girl named Meilin turns into a giant red panda whenever she gets too excited.`,
    genre: "Animation",
    rate: 7.1,
    price: 9.16,
    src: require("../assets/images/Turning.Red.jpg"),
  },
  {
    id: 5,
    title: "Don't Look Up",
    summary: `Two low-level astronomers must go on a giant media tour to warn mankind of an approaching comet that will destroy planet Earth.`,
    genre: "Sci-Fi",
    rate: 7.2,
    price: 9.99,
    src: require("../assets/images/Dont.Look.Up.jpg"),
  },
  {
    id: 6,
    title: "Sonic the Hedgehog 2",
    summary: `When the manic Dr Robotnik returns to Earth with a new ally, Knuckles the Echidna, Sonic and his new friend Tails is all that stands in their way.`,
    genre: "Adventure",
    rate: 7.0,
    price: 12.16,
    src: require("../assets/images/Sonic.The.Hedgehoh.2.jpg"),
  },
  {
    id: 7,
    title: "Fantastic Beasts: The Secrets of Dumbledore",
    summary: `The third installment of "Fantastic Beasts and Where to Find Them," which follows the continuing adventures of Newt Scamander.`,
    genre: "Fantasy",
    rate: 6.8,
    price: 14.99,
    src: require("../assets/images/Fantastic.Beast.2.jpg"),
  },
  {
    id: 8,
    title: "Ambulance",
    summary: `Two robbers steal an ambulance after their heist goes awry.`,
    genre: "Drama",
    rate: 6.4,
    price: 9.16,
    src: require("../assets/images/Ambulance.jpg"),
  },
  {
    id: 9,
    title: "Uncharted",
    summary: `Street-smart Nathan Drake is recruited by seasoned treasure hunter Victor "Sully" Sullivan to recover a fortune amassed by Ferdinand Magellan, and lost 500 years ago by the House of Moncada.`,
    genre: "Adventure",
    rate: 6.7,
    price: 17.99,
    src: require("../assets/images/Uncharted.jpg"),
  },
];
export function getMovies() {
  return movies;
}
